config/routes.rb
Rails.application.routes.draw do
  resources :combos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge2.rb
class Challenge2
  def self.sum_to_0(array)
    # your implementation goes here
    # list = []
    # combos_of_3 = array.combination(3).find { |a, b, c| a + b + c == 0 }

    # create empty list
    list = []
    
    # generate combinations
    combos_of_3 = array.combination(3)

    # find combinations that are equal to zero
    combos_of_3.each do | combo_array |
      list << combo_array if combo_array.sum == 0
    end
    

    list
  end
end

app/models/combo.rb
require_relative 'challenge2'

class Combo < ApplicationRecord
  before_save :set_result

  validates :input, format: { with: /\A\[([-]?\d+)(,([-]?\d+))*]\z/,
    message: "only accepts an integer array" }

  private

  def array_for(input_string)
    input_string.split(',').map do | string |
      string.to_i
    end  
  end

  def set_result
    self.result = Challenge2.sum_to_0(eval(input))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :set_combo, only: [:show, :edit, :update, :destroy]

  # GET /combos
  # GET /combos.json
  def index
    @combos = Combo.all
  end

  # GET /combos/1
  # GET /combos/1.json
  def show
  end

  # GET /combos/new
  def new
    @combo = Combo.new
  end

  # GET /combos/1/edit
  def edit
  end

  # POST /combos
  # POST /combos.json
  def create
    @combo = Combo.new(combo_params)

    respond_to do |format|
      if @combo.save
        format.html { redirect_to @combo, notice: 'Combo was successfully created.' }
        format.json { render :show, status: :created, location: @combo }
      else
        format.html { render :new }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /combos/1
  # PATCH/PUT /combos/1.json
  def update
    respond_to do |format|
      if @combo.update(combo_params)
        format.html { redirect_to @combo, notice: 'Combo was successfully updated.' }
        format.json { render :show, status: :ok, location: @combo }
      else
        format.html { render :edit }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /combos/1
  # DELETE /combos/1.json
  def destroy
    @combo.destroy
    respond_to do |format|
      format.html { redirect_to combos_url, notice: 'Combo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_combo
      @combo = Combo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def combo_params
      params.require(:combo).permit(:input, :result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/combos_helper.rb
module CombosHelper
end

app/views/combos/_form.html.erb
<%= form_with(model: combo, local: true) do |form| %>
  <% if combo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(combo.errors.count, "error") %> prohibited this combo from being saved:</h2>

      <ul>
      <% combo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :input %>
    <%= form.text_field :input %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/combos/edit.html.erb
<h1>Editing Combo</h1>

<%= render 'form', combo: @combo %>

<%= link_to 'Show', @combo %> |
<%= link_to 'Back', combos_path %>

app/views/combos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Combos</h1>

<table>
  <thead>
    <tr>
      <th>Input</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @combos.each do |combo| %>
      <tr>
        <td><%= combo.input %></td>
        <td><%= combo.result %></td>
        <td><%= link_to 'Show', combo %></td>
        <td><%= link_to 'Edit', edit_combo_path(combo) %></td>
        <td><%= link_to 'Destroy', combo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Combo', new_combo_path %>

app/views/combos/new.html.erb
<h1>New Combo</h1>

<%= render 'form', combo: @combo %>

<%= link_to 'Back', combos_path %>

app/views/combos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input:</strong>
  <%= @combo.input %>
</p>

<p>
  <strong>Result:</strong>
  <%= @combo.result %>
</p>

<%= link_to 'Edit', edit_combo_path(@combo) %> |
<%= link_to 'Back', combos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FhHomework06</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>